(function () {
   const LANG_STORAGE_KEY = "site-language";
   const supportedLanguages = ["en", "ru", "kz"];
   const languageLabels = {
      en: "EN",
      ru: "RU",
      kz: "KZ",
   };
   const memoryStore = {};

   function getStoredValue(key) {
      try {
         return window.localStorage?.getItem(key) || memoryStore[key] || null;
      } catch (error) {
         return memoryStore[key] || null;
      }
   }

   function setStoredValue(key, value) {
      memoryStore[key] = value;
      try {
         window.localStorage?.setItem(key, value);
      } catch (error) {
         // Storage can be unavailable in embedded preview browsers.
      }
   }

   const translations = {
      ru: {
         "AI University of Central Asia": "AI-университет Центральной Азии",
         "Admissions": "Поступление",
         "Research & Practice": "Исследования и практика",
         "Information": "Информация",
         "About": "О нас",
         "Regional Analysis": "Региональный анализ",
         "Marketing": "Маркетинг",
         "Finances": "Финансы",
         "Organizational Structure": "Организационная структура",
         "Apply Now": "Подать заявку",
         "Dark": "Темная",
         "Light": "Светлая",
         "Kazakhstan's first AI-focused university": "Первый AI-ориентированный университет Казахстана",
         "Southern Kazakhstan's first AI-focused university": "Первый AI-ориентированный университет Южного Казахстана",
         "The Future of Central Asia Starts Here.": "Будущее Центральной Азии начинается здесь.",
         "The Future of Central Asia Starts Here": "Будущее Центральной Азии начинается здесь",
         "Southern Kazakhstan's first AI-focused university, built to prepare the next generation of global tech leaders, innovators, and entrepreneurs.": "Первый AI-ориентированный университет Южного Казахстана, созданный для подготовки нового поколения глобальных технологических лидеров, инноваторов и предпринимателей.",
         "Explore Programs": "Изучить программы",
         "Future-Ready Curriculum": "Программа, готовая к будущему",
         "AI + industry from day one": "AI + индустрия с первого дня",
         "Labs, startups, internships, and English-medium learning built into the student journey.": "Лаборатории, стартапы, стажировки и обучение на английском встроены в образовательный путь студента.",
         "Important": "Важное",
         "AU blends advanced campus infrastructure, real industry labs, and a future-facing academic model.": "AU объединяет современную кампусную инфраструктуру, реальные индустриальные лаборатории и академическую модель, ориентированную на будущее.",
         "A future-ready campus designed for AI, founders, and regional impact.": "Кампус будущего для AI, основателей стартапов и регионального влияния.",
         "Mission, vision, strategy": "Миссия, видение, стратегия",
         "Why Choose AU?": "Почему AU?",
         "At AU, we bridge the gap between traditional academia and the rapidly evolving tech landscape. Students do not have to relocate to capital cities like Astana or Almaty to receive a world-class education in technology. We bring the future directly to Taraz.": "В AU мы соединяем классическое академическое образование с быстро меняющимся технологическим ландшафтом. Студентам не нужно переезжать в Астану или Алматы, чтобы получить технологическое образование мирового уровня. Мы привозим будущее прямо в Тараз.",
         "At AU, we bridge the gap between traditional academia and the rapidly evolving tech landscape. Our core philosophy is simple: Artificial Intelligence is no longer just a separate field of study—it is the foundation of every modern profession.": "В AU мы соединяем классическое академическое образование с быстро меняющимся технологическим ландшафтом. Наша основная философия проста: искусственный интеллект больше не является отдельной областью обучения — это основа каждой современной профессии.",
         "Our Vision": "Наше видение",
         "To become the premier technology and innovation hub of Central Asia, shaping a future-driven ecosystem where students solve real-world problems from day one.": "Стать ведущим технологическим и инновационным хабом Центральной Азии, формируя экосистему, где студенты решают реальные задачи с первого дня.",
         "To become the leading AI-oriented university in Central Asia, shaping globally competitive professionals and transforming Alatau into an international hub for technological innovation.": "Стать ведущим AI-ориентированным университетом Центральной Азии, формируя глобально конкурентоспособных специалистов и превращая Алатау в международный хаб технологических инноваций.",
         "Our Mission": "Наша миссия",
         "To provide industry-driven, English-medium education that empowers students with high-paying career opportunities and global mobility.": "Предоставлять образование на английском языке, основанное на потребностях индустрии, открывая студентам доступ к высокооплачиваемой карьере и глобальной мобильности.",
         "To educate the next generation of leaders in Central Asia, engineers, innovators, and entrepreneurs who can solve real-world challenges through artificial intelligence, technology, and innovation.": "Обучать новое поколение лидеров Центральной Азии, инженеров, инноваторов и предпринимателей, способных решать реальные задачи с помощью искусственного интеллекта, технологий и инноваций.",
         "Our Strategy": "Наша стратегия",
         "We integrate cutting-edge Artificial Intelligence with fundamental sectors - Agriculture, Health, Finance, and Education - combining practical lab research with direct corporate partnerships.": "Мы интегрируем передовой искусственный интеллект с ключевыми секторами - сельским хозяйством, здравоохранением, финансами и образованием - сочетая практические лабораторные исследования с прямыми корпоративными партнерствами.",
         "We integrate cutting-edge Artificial Intelligence with Agriculture, Health, Finance, Engineering and Education through practical lab research and corporate partnerships.": "Мы интегрируем передовой искусственный интеллект с сельским хозяйством, здравоохранением, финансами, инженерией и образованием через практические лабораторные исследования и корпоративные партнерства.",
         "AU by the numbers": "AU в цифрах",
         "A regional launchpad for ambitious students.": "Региональная стартовая площадка для амбициозных студентов.",
         "Undergraduate Students in Year 1": "Студентов бакалавриата в первый год",
         "Active Student Startups Projected": "Планируемых активных студенческих стартапов",
         "Industry Partners & Tech Companies": "Индустриальных партнеров и технологических компаний",
         "Guaranteed Internship Opportunities": "Гарантированные возможности стажировок",
         "AI-Focused University in the Region": "AI-ориентированный университет в регионе",
         "Regional Recruitment Hub": "Региональный центр привлечения талантов",
         "Academic programs": "Академические программы",
         "Our Education Model": "Наша образовательная модель",
         "We offer flexible, forward-thinking curriculums designed in collaboration with top tech founders and industry experts. Programs are delivered primarily in English to ensure our graduates are competitive on the global stage.": "Мы предлагаем гибкие и современные учебные программы, разработанные совместно с технологическими основателями и экспертами индустрии. Обучение ведется преимущественно на английском языке, чтобы выпускники были конкурентоспособны на глобальном рынке.",
         "Artificial Intelligence & Data Science": "Искусственный интеллект и Data Science",
         "Master advanced algorithms, machine learning, and data analytics.": "Освойте продвинутые алгоритмы, машинное обучение и аналитику данных.",
         "FinTech & Digital Banking": "FinTech и цифровой банкинг",
         "Drive innovation in the financial sector through modern software solutions.": "Развивайте инновации в финансовом секторе через современные программные решения.",
         "AgriTech & Smart Systems": "AgriTech и умные системы",
         "Apply AI for crop monitoring, predictive analytics, and sustainable drone farming.": "Применяйте AI для мониторинга посевов, предиктивной аналитики и устойчивого дрон-фермерства.",
         "HealthTech & Healthcare Analytics": "HealthTech и аналитика здравоохранения",
         "Build smart diagnostics and data systems for modern medical institutions.": "Создавайте интеллектуальную диагностику и системы данных для современных медицинских учреждений.",
         "Research & practical opportunities": "Исследования и практические возможности",
         "Beyond the Classroom: Innovation & Practice": "За пределами аудитории: инновации и практика",
         "Education at AU is built on real action. Students do not just study theory - they build products inside a live technology ecosystem.": "Образование в AU построено на реальном действии. Студенты не только изучают теорию - они создают продукты внутри живой технологической экосистемы.",
         "Education at AU is built on real action. We operate as a live technology ecosystem where students do not just study theory - they build products.": "Образование в AU построено на реальном действии. Мы работаем как живая технологическая экосистема, где студенты не просто изучают теорию - они создают продукты.",
         "Robotics & AI Labs": "Лаборатории робототехники и AI",
         "Work with state-of-the-art infrastructure and hardware from your first semester.": "Работайте с современной инфраструктурой и оборудованием с первого семестра.",
         "Startup Culture & Hackathons": "Стартап-культура и хакатоны",
         "Join innovation communities, tech festivals, and campus incubation programs.": "Присоединяйтесь к инновационным сообществам, технологическим фестивалям и инкубационным программам кампуса.",
         "Executive & Professional Network": "Профессиональная сеть",
         "Learn alongside industry leaders, business owners, researchers, and mentors.": "Учитесь рядом с лидерами индустрии, владельцами бизнеса, исследователями и наставниками.",
         "Experience campus life": "Жизнь в кампусе",
         "Your Second Home": "Ваш второй дом",
         "We provide a safe, disciplined, and vibrant environment where student life thrives. Modern dormitories, active clubs, and English-speaking networks support personal and professional growth.": "Мы создаем безопасную, дисциплинированную и живую среду, где развивается студенческая жизнь. Современные общежития, активные клубы и англоязычные сообщества поддерживают личностный и профессиональный рост.",
         "We provide a safe, disciplined, and vibrant environment where student life thrives. From modern, comfortable dormitories to active student clubs and English-speaking networks, our campus supports your personal and professional growth.": "Мы создаем безопасную, дисциплинированную и живую среду, где развивается студенческая жизнь. Современные комфортные общежития, активные студенческие клубы и англоязычные сообщества поддерживают личностный и профессиональный рост.",
         "Book a Campus Tour": "Записаться на тур по кампусу",
         "Modern dormitories": "Современные общежития",
         "English-speaking networks": "Англоязычные сообщества",
         "Student clubs": "Студенческие клубы",
         "Our partners & network": "Партнеры и сеть",
         "Trusted by Industry Leaders": "Нам доверяют лидеры индустрии",
         "We bridge academia with the corporate world. Students intern, collaborate, and secure jobs with top tech companies, banks, innovative startups, and regional enterprises.": "Мы связываем академическую среду с корпоративным миром. Студенты проходят стажировки, сотрудничают и получают работу в технологических компаниях, банках, инновационных стартапах и региональных предприятиях.",
         "We bridge academia with the corporate world. AU students regularly intern, collaborate, and secure jobs with top tech companies, banks, innovative startups, and regional enterprises.": "Мы связываем академическую среду с корпоративным миром. Студенты AU регулярно проходят стажировки, сотрудничают и получают работу в ведущих технологических компаниях, банках, инновационных стартапах и региональных предприятиях.",
         "Tech Companies": "Технологические компании",
         "Digital Banks": "Цифровые банки",
         "EdTech Startups": "EdTech-стартапы",
         "AgriTech Ventures": "AgriTech-проекты",
         "Partner Hospitals": "Партнерские больницы",
         "Latest news & blog": "Новости и блог",
         "Campus News & Insights": "Новости и идеи кампуса",
         "Inside AU": "Внутри AU",
         "How Taraz is transforming into a modern technology city.": "Как Тараз превращается в современный технологический город.",
         "How Alatau is transforming into a modern technology city.": "Как Алатау превращается в современный технологический город.",
         "Student Story": "История студента",
         "From school student to AI builder - an English improvement and tech journey.": "От школьника до AI-разработчика - путь в английском и технологиях.",
         "Announcements": "Объявления",
         "AU Olympiad results and upcoming full scholarship pipelines.": "Результаты олимпиады AU и новые полные стипендиальные треки.",
         "Ready to build your future at AU?": "Готовы строить свое будущее в AU?",
         "Admissions requirements include a motivation letter, IELTS, and ENT or SAT results. Scholarship tracks include AI Talent, Future Leaders, Girls in Tech, and Founder.": "Требования к поступлению включают мотивационное письмо, IELTS и результаты ЕНТ или SAT. Стипендиальные треки: AI Talent, Future Leaders, Girls in Tech и Founder.",
         "Contact Admissions": "Связаться с приемной комиссией",
         "Five Schools. Infinite Possibilities. A new technology future for Southern Kazakhstan.": "Пять школ. Безграничные возможности. Новое технологическое будущее Южного Казахстана.",
         "Five Schools. Infinite Possibilities. A new technology future for Kazakhstan.": "Пять школ. Безграничные возможности. Новое технологическое будущее Казахстана.",
         "Five Schools. Infinite Possibilities.": "Пять школ. Безграничные возможности.",
         "Quick Links": "Быстрые ссылки",
         "About Us": "О нас",
         "Admissions Requirements": "Требования к поступлению",
         "Scholarships": "Стипендии",
         "Student Ambassador Program": "Программа студенческих амбассадоров",
         "Contact Us": "Связаться с нами",
         "Contact Info": "Контакты",
         "Alatau, Kazakhstan": "Алатау, Казахстан",
         "Start your AI-first university journey.": "Начните свой путь в AI-университете.",
         "Industry-driven, English-medium education with 100% guaranteed internship opportunities from Year 1 for ambitious students from Southern Kazakhstan.": "Образование на английском языке, ориентированное на индустрию, со 100% гарантированными возможностями стажировок с первого года для амбициозных студентов Южного Казахстана.",
         "Clear pathways for Grade 10-11 students and parents.": "Понятные траектории для учеников 10-11 классов и их родителей.",
         "Academic structure": "Академическая структура",
         "Our Schools": "Наши школы",
         "NEXUS: School of Engineering": "NEXUS: Школа инженерии",
         "VITALIS: School of Healthcare Innovation": "VITALIS: Школа инноваций в здравоохранении",
         "QUANTUM: School of Finance & Analytics": "QUANTUM: Школа финансов и аналитики",
         "AGRONOVA: Institute of Smart Agriculture": "AGRONOVA: Институт умного сельского хозяйства",
         "LUMEN: School of Education & Human Learning": "LUMEN: Школа образования и человеческого обучения",
         "Engineering the future with AI.": "Проектируя будущее с AI.",
         "Innovating health. Improving lives.": "Инновации в здоровье. Улучшение жизни.",
         "Data-driven insights. Smarter decisions.": "Данные как основа. Умные решения.",
         "Smart farming. Sustainable future.": "Умное фермерство. Устойчивое будущее.",
         "Empowering minds. Shaping tomorrow.": "Развивая мышление. Формируя завтра.",
         "How to apply": "Как поступить",
         "Admission Requirements": "Требования к поступлению",
         "ENT or SAT scores": "Результаты ЕНТ или SAT",
         "Submit your national or international exam results for academic assessment.": "Предоставьте результаты национального или международного экзамена для академической оценки.",
         "IELTS / English test": "IELTS / тест по английскому",
         "Show English language proficiency for English-medium study.": "Подтвердите владение английским языком для обучения на английском.",
         "Motivation Letter": "Мотивационное письмо",
         "Explain your goals, interests, and why AU is the right place for your future.": "Опишите свои цели, интересы и почему AU подходит для вашего будущего.",
         "Scholarship opportunities": "Стипендиальные возможности",
         "Four pathways for exceptional students.": "Четыре трека для выдающихся студентов.",
         "AI Talent Scholarship": "Стипендия AI Talent",
         "For top AI and tech applicants with strong technical potential, competition results, or project portfolios.": "Для сильных абитуриентов в AI и технологиях с высоким техническим потенциалом, результатами конкурсов или проектным портфолио.",
         "Future Leaders Scholarship": "Стипендия Future Leaders",
         "For students with leadership records and exceptional extracurricular activities.": "Для студентов с лидерским опытом и выдающейся внеучебной активностью.",
         "Girls in Tech Scholarship": "Стипендия Girls in Tech",
         "Encouraging women in STEM through access, mentorship, and targeted support.": "Поддержка женщин в STEM через доступ, наставничество и целевую помощь.",
         "Founder Scholarship": "Стипендия Founder",
         "For young entrepreneurs, creators, and innovators building products, communities, or startups.": "Для молодых предпринимателей, создателей и инноваторов, развивающих продукты, сообщества или стартапы.",
         "Research & Hubs": "Исследования и хабы",
         "Research that becomes regional technology.": "Исследования, которые становятся региональными технологиями.",
         "Education + Tech Ecosystem.": "Экосистема образования и технологий.",
         "AU is a live innovation ecosystem that moves beyond pure theory into commercial tech products, consulting contracts, SaaS development, and B2B research.": "AU - живая инновационная экосистема, которая выходит за рамки теории к коммерческим технологическим продуктам, консалтинговым контрактам, SaaS-разработке и B2B-исследованиям.",
         "Live ecosystem": "Живая экосистема",
         "From lab research to SaaS products, consulting, and B2B innovation.": "От лабораторных исследований к SaaS-продуктам, консалтингу и B2B-инновациям.",
         "Student teams, faculty, and corporate partners work inside applied labs.": "Студенческие команды, преподаватели и корпоративные партнеры работают в прикладных лабораториях.",
         "Our operating model": "Наша операционная модель",
         "We do not just rely on tuition. AU builds an Education + Tech Ecosystem that generates real industry solutions, consulting contracts, sponsored research, and student-built products.": "Мы не опираемся только на оплату обучения. AU строит экосистему Education + Tech, которая создает реальные индустриальные решения, консалтинговые контракты, спонсируемые исследования и продукты студентов.",
         "Students work inside applied labs where corporate briefs, regional problems, and faculty research become practical prototypes, software platforms, analytics systems, and deployable products.": "Студенты работают в прикладных лабораториях, где корпоративные задачи, региональные проблемы и исследования преподавателей превращаются в прототипы, программные платформы, аналитические системы и готовые продукты.",
         "Key innovation hubs": "Ключевые инновационные хабы",
         "Where students build real products.": "Где студенты создают реальные продукты.",
         "Hardware, state-of-the-art infrastructure, and student-led tech projects from the first year of study.": "Оборудование, современная инфраструктура и студенческие технологические проекты с первого года обучения.",
         "AgriTech & Crop Analytics Hub": "Хаб AgriTech и аналитики урожая",
         "Drones, smart irrigation systems, and predictive analytics for regional agriculture and sustainable farming.": "Дроны, системы умного орошения и предиктивная аналитика для регионального сельского хозяйства и устойчивого фермерства.",
         "HealthTech & Diagnostics Lab": "Лаборатория HealthTech и диагностики",
         "Healthcare analytics and smart digital systems for hospitals, clinics, diagnostics, and patient operations.": "Аналитика здравоохранения и умные цифровые системы для больниц, клиник, диагностики и пациентских процессов.",
         "FinTech & Digital Banking Center": "Центр FinTech и цифрового банкинга",
         "Fraud detection algorithms, risk modeling, and financial data analysis systems for banks and fintech teams.": "Алгоритмы выявления мошенничества, моделирование рисков и системы анализа финансовых данных для банков и финтех-команд.",
         "SaaS & EdTech Development Unit": "Подразделение SaaS и EdTech-разработки",
         "Students and faculty build and license LMS platforms, school analytics systems, and teacher AI assistants to real schools.": "Студенты и преподаватели создают и лицензируют LMS-платформы, системы школьной аналитики и AI-ассистентов учителя для реальных школ.",
         "Vision, mission & 5-year strategy": "Видение, миссия и 5-летняя стратегия",
         "The #1 AI-focused university brand in Central Asia.": "AI-университетский бренд номер 1 в Центральной Азии.",
         "AU proves that high-quality technology education does not require moving to capital cities. The future can start from Taraz and Southern Kazakhstan.": "AU доказывает, что качественное технологическое образование не требует переезда в столичные города. Будущее может начаться в Таразе и Южном Казахстане.",
         "5-year strategy": "5-летняя стратегия",
         "Building a recognized AI brand for Kazakhstan and Central Asia.": "Создание узнаваемого AI-бренда для Казахстана и Центральной Азии.",
         "Scaling from 800 first-year undergraduate students to a regional AI innovation brand.": "Рост от 800 студентов первого набора до регионального AI-инновационного бренда.",
         "Main Vision & Goal": "Главное видение и цель",
         "Our Year 1 enrollment target is 800 undergraduate students. Over the next stage, AU grows into a vibrant home for 5,000+ active students and 100+ student startups.": "Цель первого года - 800 студентов бакалавриата. На следующем этапе AU станет активной средой для 5 000+ студентов и 100+ студенческих стартапов.",
         "The university is designed as a high-trust, English-medium, AI-focused environment where education, research, startups, and industry partnerships reinforce one another.": "Университет проектируется как среда высокого доверия с обучением на английском языке и фокусом на AI, где образование, исследования, стартапы и индустриальные партнерства усиливают друг друга.",
         "Goals spreadsheet": "Таблица целей",
         "Embedded preview of the planning sheet for institutional goals.": "Встроенный просмотр плановой таблицы институциональных целей.",
         "Open sheet": "Открыть таблицу",
         "Strategic 5-year objectives": "Стратегические цели на 5 лет",
         "Four pillars of growth.": "Четыре опоры роста.",
         "Central Asian Tech Leadership": "Технологическое лидерство в Центральной Азии",
         "Build the #1 AI brand, reach 5M+ digital users, and earn strong recognition in Kazakhstan, Uzbekistan, and Kyrgyzstan.": "Создать AI-бренд номер 1, охватить 5M+ цифровых пользователей и получить сильное признание в Казахстане, Узбекистане и Кыргызстане.",
         "Industry-Driven Curriculum": "Учебная программа, ориентированная на индустрию",
         "Develop 100+ corporate partnerships with tech companies, banks, and agrotech firms, with real practical projects from Day One.": "Развить 100+ корпоративных партнерств с технологическими компаниями, банками и агротех-фирмами, с реальными практическими проектами с первого дня.",
         "International Reputation": "Международная репутация",
         "Scale English-medium programs, international faculty, dual-degree systems, and exchange partnerships.": "Развивать англоязычные программы, международный профессорско-преподавательский состав, двойные дипломы и обменные партнерства.",
         "Regional Innovation Hub": "Региональный инновационный хаб",
         "Position Taraz and Southern Kazakhstan as emerging technology hotspots for students, founders, and employers.": "Позиционировать Тараз и Южный Казахстан как новые технологические центры для студентов, основателей и работодателей.",
         "Documents": "Документы",
         "Download strategy and reference files.": "Скачать стратегические и справочные файлы.",
         "Download": "Скачать",
         "AU Strategic Plan 2027-2031": "Стратегический план AU 2027-2031",
         "Higher Education Development Concept": "Концепция развития высшего образования",
         "Target Indicator Calculation Methodology": "Методика расчета целевых индикаторов",
         "Alatau City Master Plan": "Генеральный план города Алатау",
         "Government Resolution Reference": "Справка по постановлению Правительства",
         "Institutional strategy document.": "Документ институциональной стратегии.",
         "Reference policy document.": "Справочный документ политики.",
         "Methodology reference.": "Справочная методология.",
         "Regional development reference.": "Справочный документ регионального развития.",
         "Official document archive.": "Архив официальных документов.",
         "Institutional Information": "Институциональная информация",
         "Building the AI future of Central Asia from Alatau.": "Строим AI-будущее Центральной Азии из Алатау.",
         "Institutional information": "Институциональная информация",
         "Internal strategy & operations.": "Внутренняя стратегия и операции.",
         "A clean operational breakdown for stakeholders, institutional partners, investors, and strategic collaborators.": "Четкая операционная структура для стейкхолдеров, институциональных партнеров, инвесторов и стратегических участников.",
         "Operations": "Операции",
         "Clear strategy, scalable revenue streams, and accountable institutional structure.": "Четкая стратегия, масштабируемые источники дохода и ответственная институциональная структура.",
         "Section 1: Regional & PEST Analysis": "Раздел 1: региональный и PEST-анализ",
         "Economic and sectoral context": "Экономический и отраслевой контекст",
         "Labor market demand": "Спрос на рынке труда",
         "Education capacity and regional access": "Образовательная емкость и региональный доступ",
         "Strategic alignment with Alatau": "Стратегическое соответствие Алатау",
         "Institutional rationale": "Институциональное обоснование",
         "Regional analysis document": "Документ регионального анализа",
         "Embedded preview of the full regional analysis source document.": "Встроенный просмотр полного исходного документа регионального анализа.",
         "Open document": "Открыть документ",
         "Section 2": "Раздел 2",
         "Marketing & Funnel Strategy": "Маркетинг",
         "Awareness and regional outreach": "Узнаваемость и региональный охват",
         "Digital communication strategy": "Стратегия цифровых коммуникаций",
         "Lead generation and conversion": "Лидогенерация и конверсия",
         "Partnerships, public relations, and community development": "Партнерства, PR и развитие сообщества",
         "Reach": "Охват",
         "Leads": "Лиды",
         "Applicants": "Абитуриенты",
         "Interviews": "Интервью",
         "Offers": "Офферы",
         "Enrolled Students": "Зачисленные студенты",
         "Marketing strategy document": "Документ маркетинговой стратегии",
         "Marketing presentation": "Маркетинговая презентация",
         "Open presentation": "Открыть презентацию",
         "Embedded preview of the full marketing strategy document.": "Встроенный просмотр полного документа маркетинговой стратегии.",
         "Section 3": "Раздел 3",
         "Financial & Revenue Model": "Финансовая и доходная модель",
         "B2B Corporate Contracts": "B2B-корпоративные контракты",
         "Executive Education Programs": "Программы для руководителей",
         "Online Courses & Certifications": "Онлайн-курсы и сертификации",
         "Real Estate & Auxiliary Revenue": "Недвижимость и дополнительная выручка",
         "Conferences & Summits": "Конференции и саммиты",
         "Financial planning spreadsheet": "Таблица финансового планирования",
         "Revenue model": "Модель доходов",
         "Embedded preview of the working financial model.": "Встроенный просмотр рабочей финансовой модели.",
         "Section 4": "Раздел 4",
         "University Leadership": "Руководство университета",
         "Board of Directors": "Совет директоров",
         "Academic Councils": "Академические советы",
         "Individual School Heads": "Руководители школ",
         "Governance": "Управление",
         "Board of Trustees": "Попечительский совет",
         "Chairman of the Board of Directors, BI Group": "Председатель совета директоров BI Group",
         "Founder and CEO, Freedom Holding Corp.": "Основатель и CEO Freedom Holding Corp.",
         "Owner and Chairman, GALANZ Bottlers Holding": "Владелец и председатель GALANZ Bottlers Holding",
         "Representative, Eurasian Foods Corporation": "Представитель Eurasian Foods Corporation",
         "Representative, MEDIKER Group": "Представитель MEDIKER Group",
         "Bringing world-class expertise in large-scale infrastructure, corporate governance, and sustainable development to drive the university's physical and technological expansion.": "Привносит экспертизу мирового уровня в крупной инфраструктуре, корпоративном управлении и устойчивом развитии для физического и технологического расширения университета.",
         "A global digital fintech pioneer leading the integration of data-driven finance analytics, technology capitalization, and international market opportunities within our core programs.": "Глобальный пионер цифрового финтеха, который помогает интегрировать финансовую аналитику на основе данных, технологическую капитализацию и международные рыночные возможности в ключевые программы.",
         "A distinguished entrepreneur bridging the gap between advanced manufacturing, smart enterprise operations, and large-scale consumer-market business modeling.": "Выдающийся предприниматель, соединяющий передовое производство, умные операционные процессы предприятий и моделирование крупного потребительского рынка.",
         "Providing vital strategic alignment with Central Asia's food security sector, automated agro-industrial supply chains, and large-scale operational logistics.": "Обеспечивает стратегическую связь с сектором продовольственной безопасности Центральной Азии, автоматизированными агропромышленными цепочками поставок и крупной операционной логистикой.",
         "Guiding the university's intersection with the healthcare economy, medical asset management, and the rapid deployment of data analytics across regional healthcare networks.": "Направляет развитие университета на пересечении экономики здравоохранения, управления медицинскими активами и быстрого внедрения аналитики данных в региональных медицинских сетях.",
         "Transformational Leadership (Bass & Avolio)": "Трансформационное лидерство (Басс и Аволио)",
         "The proposed architecture moves beyond transactional management based on reward and punishment mechanisms. It is designed around transformational leadership, where institutional structures encourage initiative, intellectual growth, and individual development.": "Предлагаемая архитектура выходит за рамки транзакционного управления, основанного на механизмах вознаграждения и наказания. Она построена вокруг трансформационного лидерства, где институциональные структуры поощряют инициативу, интеллектуальный рост и индивидуальное развитие.",
         "Organizational structure map": "Карта организационной структуры",
         "Embedded preview of the institutional structure map.": "Встроенный просмотр институциональной структуры.",
         "Open map": "Открыть карту",
         "Operational clarity for partners and investors.": "Операционная ясность для партнеров и инвесторов.",
      },
      kz: {
         "AI University of Central Asia": "Орталық Азияның AI университеті",
         "Admissions": "Қабылдау",
         "Research & Practice": "Зерттеу және практика",
         "Information": "Ақпарат",
         "About": "Біз туралы",
         "Regional Analysis": "Өңірлік талдау",
         "Marketing": "Маркетинг",
         "Finances": "Қаржы",
         "Organizational Structure": "Ұйымдық құрылым",
         "Apply Now": "Өтінім беру",
         "Dark": "Қараңғы",
         "Light": "Жарық",
         "Southern Kazakhstan's first AI-focused university": "Оңтүстік Қазақстандағы алғашқы AI-бағдарлы университет",
         "The Future of Central Asia Starts Here.": "Орталық Азияның болашағы осы жерден басталады.",
         "Southern Kazakhstan's first AI-focused university, built to prepare the next generation of global tech leaders, innovators, and entrepreneurs.": "Оңтүстік Қазақстандағы алғашқы AI-бағдарлы университет жаһандық технология көшбасшыларының, инноваторлардың және кәсіпкерлердің жаңа буынын даярлау үшін құрылған.",
         "Explore Programs": "Бағдарламаларды көру",
         "Future-Ready Curriculum": "Болашаққа дайын оқу бағдарламасы",
         "AI + industry from day one": "AI + индустрия бірінші күннен",
         "Labs, startups, internships, and English-medium learning built into the student journey.": "Лабораториялар, стартаптар, тағылымдамалар және ағылшын тіліндегі оқу студент жолының бір бөлігі.",
         "Important": "Маңызды",
         "AU blends advanced campus infrastructure, real industry labs, and a future-facing academic model.": "AU заманауи кампус инфрақұрылымын, нақты индустриялық лабораторияларды және болашаққа бағытталған академиялық модельді біріктіреді.",
         "Mission, vision, strategy": "Миссия, көзқарас, стратегия",
         "Why Choose AU?": "Неліктен AU?",
         "At AU, we bridge the gap between traditional academia and the rapidly evolving tech landscape. Students do not have to relocate to capital cities like Astana or Almaty to receive a world-class education in technology. We bring the future directly to Taraz.": "AU дәстүрлі академиялық білім мен жылдам дамып жатқан технологиялық орта арасындағы алшақтықты азайтады. Студенттер әлемдік деңгейдегі технологиялық білім алу үшін Астанаға немесе Алматыға көшуге міндетті емес. Біз болашақты тікелей Таразға әкелеміз.",
         "Our Vision": "Біздің көзқарасымыз",
         "To become the premier technology and innovation hub of Central Asia, shaping a future-driven ecosystem where students solve real-world problems from day one.": "Студенттер бірінші күннен бастап нақты мәселелерді шешетін болашаққа бағытталған экожүйені қалыптастырып, Орталық Азияның жетекші технология және инновация хабына айналу.",
         "Our Mission": "Біздің миссиямыз",
         "To provide industry-driven, English-medium education that empowers students with high-paying career opportunities and global mobility.": "Студенттерге жоғары табысты мансап мүмкіндіктері мен жаһандық мобильділік беретін, индустрияға негізделген ағылшын тіліндегі білім ұсыну.",
         "Our Strategy": "Біздің стратегиямыз",
         "We integrate cutting-edge Artificial Intelligence with fundamental sectors - Agriculture, Health, Finance, and Education - combining practical lab research with direct corporate partnerships.": "Біз алдыңғы қатарлы жасанды интеллектіні ауыл шаруашылығы, денсаулық сақтау, қаржы және білім сияқты негізгі салалармен біріктіріп, практикалық лабораториялық зерттеулерді тікелей корпоративтік серіктестіктермен байланыстырамыз.",
         "AU by the numbers": "AU сандармен",
         "A regional launchpad for ambitious students.": "Амбициясы жоғары студенттерге арналған өңірлік алаң.",
         "Undergraduate Students in Year 1": "Бірінші жылы бакалавриат студенттері",
         "Active Student Startups Projected": "Жоспарланған белсенді студенттік стартаптар",
         "Industry Partners & Tech Companies": "Индустриялық серіктестер және технологиялық компаниялар",
         "Guaranteed Internship Opportunities": "Кепілдендірілген тағылымдама мүмкіндіктері",
         "AI-Focused University in the Region": "Өңірдегі AI-бағдарлы университет",
         "Regional Recruitment Hub": "Өңірлік таланттарды тарту хабы",
         "Academic programs": "Академиялық бағдарламалар",
         "Our Education Model": "Біздің білім беру моделіміз",
         "We offer flexible, forward-thinking curriculums designed in collaboration with top tech founders and industry experts. Programs are delivered primarily in English to ensure our graduates are competitive on the global stage.": "Біз жетекші технологиялық негізін қалаушылармен және индустрия сарапшыларымен бірлесіп жасалған икемді, болашаққа бағытталған оқу бағдарламаларын ұсынамыз. Бағдарламалар негізінен ағылшын тілінде жүргізіледі, бұл түлектердің жаһандық деңгейде бәсекеге қабілетті болуына көмектеседі.",
         "Artificial Intelligence & Data Science": "Жасанды интеллект және Data Science",
         "Master advanced algorithms, machine learning, and data analytics.": "Күрделі алгоритмдерді, машиналық оқытуды және деректер аналитикасын меңгеріңіз.",
         "FinTech & Digital Banking": "FinTech және цифрлық банкинг",
         "Drive innovation in the financial sector through modern software solutions.": "Қаржы секторындағы инновацияны заманауи бағдарламалық шешімдер арқылы дамытыңыз.",
         "AgriTech & Smart Systems": "AgriTech және ақылды жүйелер",
         "Apply AI for crop monitoring, predictive analytics, and sustainable drone farming.": "AI-ды егін мониторингіне, болжамды аналитикаға және тұрақты дрон-фермерлікке қолданыңыз.",
         "HealthTech & Healthcare Analytics": "HealthTech және медицина аналитикасы",
         "Build smart diagnostics and data systems for modern medical institutions.": "Заманауи медициналық ұйымдарға арналған ақылды диагностика және деректер жүйелерін жасаңыз.",
         "Research & practical opportunities": "Зерттеу және практикалық мүмкіндіктер",
         "Beyond the Classroom: Innovation & Practice": "Аудиториядан тыс: инновация және практика",
         "Education at AU is built on real action. Students do not just study theory - they build products inside a live technology ecosystem.": "AU-дағы білім нақты әрекетке негізделген. Студенттер тек теория оқымайды - олар тірі технологиялық экожүйеде өнім жасайды.",
         "Robotics & AI Labs": "Робототехника және AI лабораториялары",
         "Work with state-of-the-art infrastructure and hardware from your first semester.": "Бірінші семестрден бастап заманауи инфрақұрылым және жабдықпен жұмыс істеңіз.",
         "Startup Culture & Hackathons": "Стартап мәдениеті және хакатондар",
         "Join innovation communities, tech festivals, and campus incubation programs.": "Инновациялық қауымдастықтарға, технология фестивальдеріне және кампус инкубациялық бағдарламаларына қосылыңыз.",
         "Executive & Professional Network": "Кәсіби желі",
         "Learn alongside industry leaders, business owners, researchers, and mentors.": "Индустрия көшбасшыларымен, бизнес иелерімен, зерттеушілермен және менторлармен бірге үйреніңіз.",
         "Experience campus life": "Кампус өмірі",
         "Your Second Home": "Сіздің екінші үйіңіз",
         "We provide a safe, disciplined, and vibrant environment where student life thrives. Modern dormitories, active clubs, and English-speaking networks support personal and professional growth.": "Біз студенттік өмір дамитын қауіпсіз, тәртіпті және белсенді орта жасаймыз. Заманауи жатақханалар, клубтар және ағылшын тілді желілер жеке әрі кәсіби өсуге қолдау көрсетеді.",
         "Book a Campus Tour": "Кампус турына жазылу",
         "Modern dormitories": "Заманауи жатақханалар",
         "English-speaking networks": "Ағылшын тілді қауымдастықтар",
         "Student clubs": "Студенттік клубтар",
         "Our partners & network": "Серіктестер және желі",
         "Trusted by Industry Leaders": "Индустрия көшбасшылары сенім білдіреді",
         "We bridge academia with the corporate world. Students intern, collaborate, and secure jobs with top tech companies, banks, innovative startups, and regional enterprises.": "Біз академиялық ортаны корпоративтік әлеммен байланыстырамыз. Студенттер технологиялық компанияларда, банктерде, инновациялық стартаптарда және өңірлік кәсіпорындарда тағылымдамадан өтіп, жұмыс табады.",
         "Tech Companies": "Технологиялық компаниялар",
         "Digital Banks": "Цифрлық банктер",
         "EdTech Startups": "EdTech стартаптары",
         "AgriTech Ventures": "AgriTech жобалары",
         "Partner Hospitals": "Серіктес ауруханалар",
         "Latest news & blog": "Жаңалықтар және блог",
         "Campus News & Insights": "Кампус жаңалықтары",
         "Inside AU": "AU ішінде",
         "How Taraz is transforming into a modern technology city.": "Тараз заманауи технологиялық қалаға қалай айналып келеді.",
         "Student Story": "Студент тарихы",
         "From school student to AI builder - an English improvement and tech journey.": "Мектеп оқушысынан AI жасаушыға дейін - ағылшын мен технологиядағы жол.",
         "Announcements": "Хабарландырулар",
         "AU Olympiad results and upcoming full scholarship pipelines.": "AU олимпиадасының нәтижелері және алдағы толық стипендия тректері.",
         "Ready to build your future at AU?": "AU-да болашағыңызды құруға дайынсыз ба?",
         "Admissions requirements include a motivation letter, IELTS, and ENT or SAT results. Scholarship tracks include AI Talent, Future Leaders, Girls in Tech, and Founder.": "Қабылдау талаптарына мотивациялық хат, IELTS және ҰБТ немесе SAT нәтижелері кіреді. Стипендиялық тректер: AI Talent, Future Leaders, Girls in Tech және Founder.",
         "Contact Admissions": "Қабылдау бөліміне жазу",
         "Five Schools. Infinite Possibilities. A new technology future for Southern Kazakhstan.": "Бес мектеп. Шексіз мүмкіндіктер. Оңтүстік Қазақстанның жаңа технологиялық болашағы.",
         "Five Schools. Infinite Possibilities.": "Бес мектеп. Шексіз мүмкіндіктер.",
         "Quick Links": "Жылдам сілтемелер",
         "Admissions Requirements": "Қабылдау талаптары",
         "Scholarships": "Стипендиялар",
         "Student Ambassador Program": "Студенттік амбассадор бағдарламасы",
         "Contact Us": "Байланысу",
         "Contact Info": "Байланыс ақпараты",
         "Alatau, Kazakhstan": "Алатау, Қазақстан",
         "Start your AI-first university journey.": "AI-first университет жолыңызды бастаңыз.",
         "Industry-driven, English-medium education with 100% guaranteed internship opportunities from Year 1 for ambitious students from Southern Kazakhstan.": "Оңтүстік Қазақстанның амбициясы жоғары студенттері үшін индустрияға бағытталған, ағылшын тіліндегі білім және бірінші жылдан бастап 100% тағылымдама мүмкіндіктері.",
         "Clear pathways for Grade 10-11 students and parents.": "10-11 сынып оқушылары мен ата-аналарға арналған түсінікті жолдар.",
         "Academic structure": "Академиялық құрылым",
         "Our Schools": "Біздің мектептер",
         "Engineering the future with AI.": "Болашақты AI арқылы инженерлеу.",
         "Innovating health. Improving lives.": "Денсаулықтағы инновация. Өмір сапасын жақсарту.",
         "Data-driven insights. Smarter decisions.": "Деректерге негізделген түсінік. Ақылды шешімдер.",
         "Smart farming. Sustainable future.": "Ақылды фермерлік. Тұрақты болашақ.",
         "Empowering minds. Shaping tomorrow.": "Ой-сананы дамыту. Ертеңді қалыптастыру.",
         "How to apply": "Қалай түсуге болады",
         "Admission Requirements": "Қабылдау талаптары",
         "ENT or SAT scores": "ҰБТ немесе SAT нәтижелері",
         "Submit your national or international exam results for academic assessment.": "Академиялық бағалау үшін ұлттық немесе халықаралық емтихан нәтижелерін жіберіңіз.",
         "IELTS / English test": "IELTS / ағылшын тілі тесті",
         "Show English language proficiency for English-medium study.": "Ағылшын тіліндегі оқу үшін тіл деңгейіңізді көрсетіңіз.",
         "Motivation Letter": "Мотивациялық хат",
         "Explain your goals, interests, and why AU is the right place for your future.": "Мақсаттарыңызды, қызығушылықтарыңызды және неге AU сіздің болашағыңызға дұрыс орын екенін түсіндіріңіз.",
         "Scholarship opportunities": "Стипендиялық мүмкіндіктер",
         "Four pathways for exceptional students.": "Ерекше студенттерге арналған төрт бағыт.",
         "AI Talent Scholarship": "AI Talent стипендиясы",
         "For top AI and tech applicants with strong technical potential, competition results, or project portfolios.": "Техникалық әлеуеті жоғары, байқау нәтижелері немесе жобалық портфолиосы бар AI және технология бағытындағы үздік талапкерлерге арналған.",
         "Future Leaders Scholarship": "Future Leaders стипендиясы",
         "For students with leadership records and exceptional extracurricular activities.": "Көшбасшылық тәжірибесі және ерекше сабақтан тыс белсенділігі бар студенттерге арналған.",
         "Girls in Tech Scholarship": "Girls in Tech стипендиясы",
         "Encouraging women in STEM through access, mentorship, and targeted support.": "STEM саласындағы әйелдерді қолжетімділік, менторлық және арнайы қолдау арқылы ынталандыру.",
         "Founder Scholarship": "Founder стипендиясы",
         "For young entrepreneurs, creators, and innovators building products, communities, or startups.": "Өнім, қауымдастық немесе стартап құратын жас кәсіпкерлерге, креаторларға және инноваторларға арналған.",
         "Research & Hubs": "Зерттеу және хабтар",
         "Research that becomes regional technology.": "Өңірлік технологияға айналатын зерттеу.",
         "Education + Tech Ecosystem.": "Білім + технология экожүйесі.",
         "AU is a live innovation ecosystem that moves beyond pure theory into commercial tech products, consulting contracts, SaaS development, and B2B research.": "AU - таза теориядан коммерциялық технологиялық өнімдерге, консалтингтік келісімдерге, SaaS әзірлеуге және B2B зерттеуге өтетін тірі инновациялық экожүйе.",
         "Live ecosystem": "Тірі экожүйе",
         "Student teams, faculty, and corporate partners work inside applied labs.": "Студенттік командалар, оқытушылар және корпоративтік серіктестер қолданбалы лабораторияларда жұмыс істейді.",
         "Our operating model": "Біздің операциялық модель",
         "We do not just rely on tuition. AU builds an Education + Tech Ecosystem that generates real industry solutions, consulting contracts, sponsored research, and student-built products.": "Біз тек оқу ақысына сүйенбейміз. AU нақты индустриялық шешімдер, консалтингтік келісімдер, демеушілік зерттеулер және студенттік өнімдер жасайтын Education + Tech экожүйесін құрады.",
         "Students work inside applied labs where corporate briefs, regional problems, and faculty research become practical prototypes, software platforms, analytics systems, and deployable products.": "Студенттер қолданбалы лабораторияларда жұмыс істейді, онда корпоративтік тапсырмалар, өңірлік мәселелер және оқытушылар зерттеуі практикалық прототиптерге, бағдарламалық платформаларға, аналитикалық жүйелерге және іске қосылатын өнімдерге айналады.",
         "Key innovation hubs": "Негізгі инновациялық хабтар",
         "Where students build real products.": "Студенттер нақты өнім жасайтын орын.",
         "Hardware, state-of-the-art infrastructure, and student-led tech projects from the first year of study.": "Жабдық, заманауи инфрақұрылым және оқу бірінші жылынан бастап студенттік технологиялық жобалар.",
         "AgriTech & Crop Analytics Hub": "AgriTech және егін аналитикасы хабы",
         "Drones, smart irrigation systems, and predictive analytics for regional agriculture and sustainable farming.": "Өңірлік ауыл шаруашылығы және тұрақты фермерлік үшін дрондар, ақылды суару жүйелері және болжамды аналитика.",
         "HealthTech & Diagnostics Lab": "HealthTech және диагностика лабораториясы",
         "Healthcare analytics and smart digital systems for hospitals, clinics, diagnostics, and patient operations.": "Ауруханалар, клиникалар, диагностика және пациент процестері үшін медицина аналитикасы және ақылды цифрлық жүйелер.",
         "FinTech & Digital Banking Center": "FinTech және цифрлық банкинг орталығы",
         "Fraud detection algorithms, risk modeling, and financial data analysis systems for banks and fintech teams.": "Банктер мен финтех командаларына арналған алаяқтықты анықтау алгоритмдері, тәуекел модельдеуі және қаржылық деректерді талдау жүйелері.",
         "SaaS & EdTech Development Unit": "SaaS және EdTech әзірлеу бөлімі",
         "Students and faculty build and license LMS platforms, school analytics systems, and teacher AI assistants to real schools.": "Студенттер мен оқытушылар нақты мектептерге LMS платформаларын, мектеп аналитикасы жүйелерін және мұғалімге арналған AI ассистенттерін жасап, лицензиялайды.",
         "Vision, mission & 5-year strategy": "Көзқарас, миссия және 5 жылдық стратегия",
         "The #1 AI-focused university brand in Central Asia.": "Орталық Азиядағы нөмірі 1 AI-бағдарлы университет бренді.",
         "AU proves that high-quality technology education does not require moving to capital cities. The future can start from Taraz and Southern Kazakhstan.": "AU сапалы технологиялық білім алу үшін астана қалаларына көшу міндетті емес екенін дәлелдейді. Болашақ Тараз бен Оңтүстік Қазақстаннан басталуы мүмкін.",
         "5-year strategy": "5 жылдық стратегия",
         "Scaling from 800 first-year undergraduate students to a regional AI innovation brand.": "800 бірінші курс студентінен өңірлік AI инновация брендіне дейін өсу.",
         "Main Vision & Goal": "Негізгі көзқарас және мақсат",
         "Our Year 1 enrollment target is 800 undergraduate students. Over the next stage, AU grows into a vibrant home for 5,000+ active students and 100+ student startups.": "Бірінші жылдағы қабылдау мақсаты - 800 бакалавриат студенті. Келесі кезеңде AU 5 000+ белсенді студент пен 100+ студенттік стартапқа арналған ортаға айналады.",
         "The university is designed as a high-trust, English-medium, AI-focused environment where education, research, startups, and industry partnerships reinforce one another.": "Университет ағылшын тіліндегі, AI-ға бағытталған, сенімі жоғары орта ретінде жобаланған, онда білім, зерттеу, стартаптар және индустриялық серіктестіктер бірін-бірі күшейтеді.",
         "Goals spreadsheet": "Мақсаттар кестесі",
         "Embedded preview of the planning sheet for institutional goals.": "Институционалдық мақсаттарға арналған жоспарлау кестесінің кірістірілген көрінісі.",
         "Open sheet": "Кестені ашу",
         "Strategic 5-year objectives": "5 жылдық стратегиялық мақсаттар",
         "Four pillars of growth.": "Өсудің төрт тірегі.",
         "Central Asian Tech Leadership": "Орталық Азиядағы технологиялық көшбасшылық",
         "Build the #1 AI brand, reach 5M+ digital users, and earn strong recognition in Kazakhstan, Uzbekistan, and Kyrgyzstan.": "Нөмірі 1 AI брендін құру, 5M+ цифрлық пайдаланушыға жету және Қазақстан, Өзбекстан, Қырғызстанда мықты танымалдыққа ие болу.",
         "Industry-Driven Curriculum": "Индустрияға негізделген оқу бағдарламасы",
         "Develop 100+ corporate partnerships with tech companies, banks, and agrotech firms, with real practical projects from Day One.": "Технологиялық компаниялармен, банктермен және агротех фирмаларымен 100+ корпоративтік серіктестік дамыту, бірінші күннен нақты практикалық жобалармен.",
         "International Reputation": "Халықаралық бедел",
         "Scale English-medium programs, international faculty, dual-degree systems, and exchange partnerships.": "Ағылшын тіліндегі бағдарламаларды, халықаралық оқытушыларды, қос диплом жүйелерін және алмасу серіктестіктерін кеңейту.",
         "Regional Innovation Hub": "Өңірлік инновациялық хаб",
         "Position Taraz and Southern Kazakhstan as emerging technology hotspots for students, founders, and employers.": "Тараз бен Оңтүстік Қазақстанды студенттер, негізін қалаушылар және жұмыс берушілер үшін жаңа технологиялық орталықтар ретінде таныту.",
         "Documents": "Құжаттар",
         "Download strategy and reference files.": "Стратегиялық және анықтамалық файлдарды жүктеу.",
         "Download": "Жүктеу",
         "Institutional strategy document.": "Институционалдық стратегия құжаты.",
         "Reference policy document.": "Саясат бойынша анықтамалық құжат.",
         "Methodology reference.": "Әдістемелік анықтама.",
         "Regional development reference.": "Өңірлік даму бойынша анықтама.",
         "Official document archive.": "Ресми құжаттар архиві.",
         "Institutional Information": "Институционалдық ақпарат",
         "Building the AI future of Central Asia from Alatau.": "Орталық Азияның AI болашағын Алатаудан құру.",
         "Institutional information": "Институционалдық ақпарат",
         "Internal strategy & operations.": "Ішкі стратегия және операциялар.",
         "A clean operational breakdown for stakeholders, institutional partners, investors, and strategic collaborators.": "Стейкхолдерлерге, институционалдық серіктестерге, инвесторларға және стратегиялық әріптестерге арналған нақты операциялық құрылым.",
         "Operations": "Операциялар",
         "Clear strategy, scalable revenue streams, and accountable institutional structure.": "Нақты стратегия, масштабталатын табыс ағындары және жауапты институционалдық құрылым.",
         "Section 1: Regional & PEST Analysis": "1-бөлім: өңірлік және PEST талдау",
         "Economic and sectoral context": "Экономикалық және салалық контекст",
         "Labor market demand": "Еңбек нарығындағы сұраныс",
         "Education capacity and regional access": "Білім беру әлеуеті және өңірлік қолжетімділік",
         "Strategic alignment with Alatau": "Алатаумен стратегиялық сәйкестік",
         "Institutional rationale": "Институционалдық негіздеме",
         "Regional analysis document": "Өңірлік талдау құжаты",
         "Embedded preview of the full regional analysis source document.": "Өңірлік талдаудың толық бастапқы құжатының кірістірілген көрінісі.",
         "Open document": "Құжатты ашу",
         "Section 2": "2-бөлім",
         "Marketing & Funnel Strategy": "Маркетинг",
         "Awareness and regional outreach": "Танымалдық және өңірлік қамту",
         "Digital communication strategy": "Цифрлық коммуникация стратегиясы",
         "Lead generation and conversion": "Лидогенерация және конверсия",
         "Partnerships, public relations, and community development": "Серіктестік, PR және қауымдастық дамыту",
         "Reach": "Қамту",
         "Leads": "Лидтер",
         "Applicants": "Талапкерлер",
         "Interviews": "Сұхбаттар",
         "Offers": "Ұсыныстар",
         "Enrolled Students": "Қабылданған студенттер",
         "Marketing strategy document": "Маркетинг стратегиясы құжаты",
         "Marketing presentation": "Маркетинг презентациясы",
         "Open presentation": "Презентацияны ашу",
         "Embedded preview of the full marketing strategy document.": "Маркетинг стратегиясының толық құжатының кірістірілген көрінісі.",
         "Section 3": "3-бөлім",
         "Financial & Revenue Model": "Қаржылық және табыс моделі",
         "B2B Corporate Contracts": "B2B корпоративтік келісімдер",
         "Executive Education Programs": "Басшыларға арналған білім беру бағдарламалары",
         "Online Courses & Certifications": "Онлайн курстар және сертификаттар",
         "Real Estate & Auxiliary Revenue": "Жылжымайтын мүлік және қосымша табыс",
         "Conferences & Summits": "Конференциялар және саммиттер",
         "Financial planning spreadsheet": "Қаржылық жоспарлау кестесі",
         "Revenue model": "Табыс моделі",
         "Embedded preview of the working financial model.": "Жұмыс қаржылық моделінің кірістірілген көрінісі.",
         "Section 4": "4-бөлім",
         "University Leadership": "Университет басшылығы",
         "Board of Directors": "Директорлар кеңесі",
         "Academic Councils": "Академиялық кеңестер",
         "Individual School Heads": "Мектеп жетекшілері",
         "Governance": "Басқару",
         "Board of Trustees": "Қамқоршылар кеңесі",
         "Chairman of the Board of Directors, BI Group": "BI Group директорлар кеңесінің төрағасы",
         "Founder and CEO, Freedom Holding Corp.": "Freedom Holding Corp. негізін қалаушы және CEO",
         "Owner and Chairman, GALANZ Bottlers Holding": "GALANZ Bottlers Holding иесі және төрағасы",
         "Representative, Eurasian Foods Corporation": "Eurasian Foods Corporation өкілі",
         "Representative, MEDIKER Group": "MEDIKER Group өкілі",
         "Kazakhstan's first AI-focused university": "Қазақстандағы алғашқы AI-бағдарлы университет",
         "The Future of Central Asia Starts Here": "Орталық Азияның болашағы осы жерден басталады",
         "A future-ready campus designed for AI, founders, and regional impact.": "AI, стартап негізін қалаушылар және өңірлік әсер үшін жобаланған болашаққа дайын кампус.",
         "At AU, we bridge the gap between traditional academia and the rapidly evolving tech landscape. Our core philosophy is simple: Artificial Intelligence is no longer just a separate field of study—it is the foundation of every modern profession.": "AU дәстүрлі академиялық білім мен тез дамып жатқан технологиялық орта арасын байланыстырады. Біздің негізгі философиямыз қарапайым: жасанды интеллект енді жеке оқу бағыты ғана емес, әрбір заманауи мамандықтың негізі.",
         "To become the leading AI-oriented university in Central Asia, shaping globally competitive professionals and transforming Alatau into an international hub for technological innovation.": "Орталық Азиядағы жетекші AI-бағдарлы университетке айналып, жаһандық бәсекеге қабілетті мамандарды қалыптастыру және Алатауды технологиялық инновациялардың халықаралық хабына айналдыру.",
         "To educate the next generation of leaders in Central Asia, engineers, innovators, and entrepreneurs who can solve real-world challenges through artificial intelligence, technology, and innovation.": "Жасанды интеллект, технология және инновация арқылы нақты мәселелерді шеше алатын Орталық Азияның жаңа буын көшбасшыларын, инженерлерін, инноваторларын және кәсіпкерлерін оқыту.",
         "We integrate cutting-edge Artificial Intelligence with Agriculture, Health, Finance, Engineering and Education through practical lab research and corporate partnerships.": "Біз алдыңғы қатарлы жасанды интеллектіні ауыл шаруашылығы, денсаулық сақтау, қаржы, инженерия және біліммен практикалық зертханалық зерттеулер мен корпоративтік серіктестіктер арқылы біріктіреміз.",
         "Education at AU is built on real action. We operate as a live technology ecosystem where students do not just study theory - they build products.": "AU-дағы білім нақты әрекетке негізделген. Біз студенттер теорияны жай ғана оқымай, өнім жасайтын тірі технологиялық экожүйе ретінде жұмыс істейміз.",
         "We provide a safe, disciplined, and vibrant environment where student life thrives. From modern, comfortable dormitories to active student clubs and English-speaking networks, our campus supports your personal and professional growth.": "Біз студенттік өмір дамитын қауіпсіз, тәртіпті және белсенді орта ұсынамыз. Заманауи әрі жайлы жатақханалардан бастап белсенді студенттік клубтар мен ағылшын тіліндегі қауымдастықтарға дейін кампус жеке және кәсіби өсуіңізді қолдайды.",
         "We bridge academia with the corporate world. AU students regularly intern, collaborate, and secure jobs with top tech companies, banks, innovative startups, and regional enterprises.": "Біз академиялық ортаны корпоративтік әлеммен байланыстырамыз. AU студенттері жетекші технологиялық компанияларда, банктерде, инновациялық стартаптарда және өңірлік кәсіпорындарда тұрақты түрде тағылымдамадан өтіп, ынтымақтасып, жұмысқа орналасады.",
         "How Alatau is transforming into a modern technology city.": "Алатаудың заманауи технологиялық қалаға айналуы.",
         "Five Schools. Infinite Possibilities. A new technology future for Kazakhstan.": "Бес мектеп. Шексіз мүмкіндіктер. Қазақстан үшін жаңа технологиялық болашақ.",
         "About Us": "Біз туралы",
         "NEXUS: School of Engineering": "NEXUS: Инженерия мектебі",
         "VITALIS: School of Healthcare Innovation": "VITALIS: Денсаулық сақтау инновациялары мектебі",
         "QUANTUM: School of Finance & Analytics": "QUANTUM: Қаржы және аналитика мектебі",
         "AGRONOVA: Institute of Smart Agriculture": "AGRONOVA: Ақылды ауыл шаруашылығы институты",
         "LUMEN: School of Education & Human Learning": "LUMEN: Білім және адам оқуы мектебі",
         "From lab research to SaaS products, consulting, and B2B innovation.": "Лабораториялық зерттеуден SaaS өнімдеріне, консалтингке және B2B инновациясына дейін.",
         "Building a recognized AI brand for Kazakhstan and Central Asia.": "Қазақстан мен Орталық Азия үшін танымал AI брендін қалыптастыру.",
         "AU Strategic Plan 2027-2031": "AU стратегиялық жоспары 2027-2031",
         "Higher Education Development Concept": "Жоғары білім беруді дамыту тұжырымдамасы",
         "Target Indicator Calculation Methodology": "Нысаналы индикаторларды есептеу әдістемесі",
         "Alatau City Master Plan": "Алатау қаласының бас жоспары",
         "Government Resolution Reference": "Үкімет қаулысы бойынша анықтама",
         "Bringing world-class expertise in large-scale infrastructure, corporate governance, and sustainable development to drive the university's physical and technological expansion.": "Университеттің физикалық және технологиялық кеңеюін ілгерілету үшін ірі инфрақұрылым, корпоративтік басқару және тұрақты даму саласындағы әлемдік деңгейдегі тәжірибені енгізеді.",
         "A global digital fintech pioneer leading the integration of data-driven finance analytics, technology capitalization, and international market opportunities within our core programs.": "Негізгі бағдарламаларға деректерге негізделген қаржы аналитикасын, технологиялық капиталдандыруды және халықаралық нарық мүмкіндіктерін енгізуге жетекшілік ететін жаһандық цифрлық финтех пионері.",
         "A distinguished entrepreneur bridging the gap between advanced manufacturing, smart enterprise operations, and large-scale consumer-market business modeling.": "Алдыңғы қатарлы өндіріс, ақылды кәсіпорын операциялары және ірі тұтыну нарығын модельдеу арасын байланыстыратын көрнекті кәсіпкер.",
         "Providing vital strategic alignment with Central Asia's food security sector, automated agro-industrial supply chains, and large-scale operational logistics.": "Орталық Азияның азық-түлік қауіпсіздігі секторымен, автоматтандырылған агроөнеркәсіптік жеткізу тізбектерімен және ірі операциялық логистикамен маңызды стратегиялық үйлесімділікті қамтамасыз етеді.",
         "Guiding the university's intersection with the healthcare economy, medical asset management, and the rapid deployment of data analytics across regional healthcare networks.": "Университеттің денсаулық сақтау экономикасы, медициналық активтерді басқару және өңірлік медициналық желілерде деректер аналитикасын жылдам енгізу бағыттарындағы дамуын бағыттайды.",
         "Transformational Leadership (Bass & Avolio)": "Трансформациялық көшбасшылық (Басс және Аволио)",
         "The proposed architecture moves beyond transactional management based on reward and punishment mechanisms. It is designed around transformational leadership, where institutional structures encourage initiative, intellectual growth, and individual development.": "Ұсынылған архитектура марапаттау және жазалау механизмдеріне негізделген транзакциялық басқарудан асып түседі. Ол бастаманы, интеллектуалдық өсуді және жеке дамуды ынталандыратын институционалдық құрылымдары бар трансформациялық көшбасшылыққа негізделген.",
         "Operational clarity for partners and investors.": "Серіктестер мен инвесторларға арналған операциялық айқындық.",
         "Organizational structure map": "Ұйымдық құрылым картасы",
         "Embedded preview of the institutional structure map.": "Институционалдық құрылымның кірістірілген көрінісі.",
         "Open map": "Картаны ашу",
      },
   };

   function normalize(value) {
      return value.replace(/\s+/g, " ").trim();
   }

   function currentLanguage() {
      const saved = getStoredValue(LANG_STORAGE_KEY) || "en";
      return supportedLanguages.includes(saved) ? saved : "en";
   }

   function getTranslatableElements() {
      return Array.from(document.body.querySelectorAll("a, button span, h1, h2, h3, p, small, figcaption span, figcaption strong, article span, .hero-panel span, .hero-panel strong, .funnel-card span, .partner-strip span"));
   }

   function rememberSource(element) {
      const text = normalize(element.textContent || "");
      if (!text || element.closest(".language-switcher")) return null;
      if (!element.dataset.i18nSource && (translations.ru[text] || translations.kz[text] || text === "EN" || text === "RU" || text === "KZ")) {
         element.dataset.i18nSource = text;
      }
      return element.dataset.i18nSource || null;
   }

   function applyLanguage(lang) {
      document.documentElement.lang = lang === "kz" ? "kk" : lang;
      document.body.dataset.lang = lang;
      getTranslatableElements().forEach((element) => {
         const source = rememberSource(element);
         if (!source) return;
         const nextText = lang === "en" ? source : translations[lang][source] || source;
         if (element.textContent !== nextText) {
            element.textContent = nextText;
         }
      });
      document.querySelectorAll(".language-option").forEach((button) => {
         const isActive = button.dataset.lang === lang;
         button.classList.toggle("is-active", isActive);
         button.setAttribute("aria-pressed", String(isActive));
      });
      setStoredValue(LANG_STORAGE_KEY, lang);
   }

   function buildSwitcher() {
      const headerActions = document.querySelector(".header-actions");
      if (!headerActions || headerActions.querySelector(".language-switcher")) return;

      const switcher = document.createElement("div");
      switcher.className = "language-switcher";
      switcher.setAttribute("aria-label", "Language switcher");

      supportedLanguages.forEach((lang) => {
         const button = document.createElement("button");
         button.type = "button";
         button.className = "language-option";
         button.dataset.lang = lang;
         button.textContent = languageLabels[lang];
         button.setAttribute("aria-label", `Switch language to ${languageLabels[lang]}`);
         button.addEventListener("click", () => applyLanguage(lang));
         switcher.appendChild(button);
      });

      headerActions.prepend(switcher);
   }

   document.addEventListener("DOMContentLoaded", () => {
      buildSwitcher();
      applyLanguage(currentLanguage());

      const themeToggle = document.querySelector(".theme-toggle");
      if (themeToggle) {
         const observer = new MutationObserver(() => applyLanguage(currentLanguage()));
         observer.observe(themeToggle, { childList: true, subtree: true, characterData: true });
      }
   });
})();
